name: My first Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        #Steps are runing in series
        steps:
        - name: Checkout Step #a fundamental component used to clone a repository into the workflow's runner
          uses: actions/checkout@v4

        - name: List and read file
          run: |
            echo "My first GitHub Actions"
            ls -ltra
            cat README.md

        # - name: List files
        #   run: ls

        # - name: Read file
        #   run: cat README.md


