name: My first Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        #Steps are runing in series
        steps:
        - name: Welcome message
          run: echo "My first GitHub Actions"

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md


