name: Generate ASCII Artwork

on:
   - workflow_dispatch
   - push

jobs:
    build_job_1:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - uses: actions/upload-artifact@v4
          with:
            name: dragon-artifact
            path: dragon.txt


    test_job_2:
        runs-on: ubuntu-latest
        needs: build_job_1
        steps:
        - uses: actions/download-artifact@v4
          with:
            name: dragon-artifact
        - name: Sleep for 10 seconds
          run: sleep 10

        - name: Test file Exists
          run: grep -i "dragon" dragon.txt
        
    
    deploy_job_3:
        runs-on: ubuntu-latest
        needs: test_job_2
        concurrency: 
            group: ascii-deployment
            cancel-in-progress: true
        steps:
        - uses: actions/download-artifact@v4
          with:
            name: dragon-artifact
        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: |
            echo Deploying... .
            sleep 60